"""
PropManager — Posting Engine Models
SAP RE-FX RERAPP-inspired batch posting system.
"""

from sqlalchemy import (
    Column, Integer, String, Float, Date, DateTime, Text,
    Enum, ForeignKey, Boolean, Numeric, JSON
)
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.database import Base
import enum


class PostingRunStatus(str, enum.Enum):
    pending   = "pending"
    running   = "running"
    completed = "completed"
    failed    = "failed"
    reversed  = "reversed"


class PostingEntryType(str, enum.Enum):
    base_rent        = "base_rent"
    service_charge   = "service_charge"
    advance_payment  = "advance_payment"
    flat_rate        = "flat_rate"
    sales_based_rent = "sales_based_rent"
    markup_fee       = "markup_fee"
    rent_free        = "rent_free"
    abatement        = "abatement"
    ipc_adjustment   = "ipc_adjustment"
    scs_settlement   = "scs_settlement"
    vacancy_cost     = "vacancy_cost"
    deposit_charge   = "deposit_charge"
    ifrs16_interest  = "ifrs16_interest"
    ifrs16_amort     = "ifrs16_amort"
    catchup          = "catchup"


class PostingRun(Base):
    """
    One run of the RERAPP-style posting engine.
    Tracks period, modules run, results and errors.
    """
    __tablename__ = "re_posting_runs"

    id             = Column(Integer, primary_key=True, index=True)
    org_id = Column(Integer, ForeignKey("organizations.id"), nullable=True, index=True)
    period_from    = Column(Date, nullable=False)
    period_to      = Column(Date, nullable=False)
    module         = Column(String(50), default="all")  # all|rent|scs|sales|ifrs16|vacancy
    status         = Column(Enum(PostingRunStatus), default=PostingRunStatus.pending)
    dry_run        = Column(Boolean, default=False)
    triggered_by   = Column(Integer, ForeignKey("users.id"), nullable=True)

    total_entries  = Column(Integer, default=0)
    total_amount   = Column(Numeric(18, 2), default=0)
    error_count    = Column(Integer, default=0)
    errors         = Column(JSON, default=list)        # List of error messages
    summary        = Column(JSON, default=dict)        # Per-type breakdown

    started_at     = Column(DateTime(timezone=True), server_default=func.now())
    completed_at   = Column(DateTime(timezone=True), nullable=True)

    entries        = relationship("PostingEntry", back_populates="posting_run")


class PostingEntry(Base):
    """
    One accounting entry generated by a posting run.
    Analogous to a SAP FI document line.
    """
    __tablename__ = "re_posting_entries"

    id              = Column(Integer, primary_key=True, index=True)
    posting_run_id  = Column(Integer, ForeignKey("re_posting_runs.id"), nullable=False)
    contract_id     = Column(Integer, ForeignKey("re_contracts.id"), nullable=True)
    condition_id    = Column(Integer, ForeignKey("re_conditions.id"), nullable=True)
    rental_object_id= Column(Integer, ForeignKey("re_rental_objects.id"), nullable=True)

    entry_type      = Column(Enum(PostingEntryType), nullable=False)
    period_from     = Column(Date, nullable=False)
    period_to       = Column(Date, nullable=False)

    amount          = Column(Numeric(18, 4), nullable=False)
    currency        = Column(String(10), default="USD")
    amount_base     = Column(Numeric(18, 4))   # Converted to base currency
    fx_rate         = Column(Float, default=1.0)

    description     = Column(String(500))
    is_catchup      = Column(Boolean, default=False)
    is_reversal     = Column(Boolean, default=False)
    reversed_entry_id = Column(Integer, ForeignKey("re_posting_entries.id"), nullable=True)

    posted          = Column(Boolean, default=False)  # False if dry_run
    created_at      = Column(DateTime(timezone=True), server_default=func.now())

    posting_run     = relationship("PostingRun", back_populates="entries")


class FxRate(Base):
    """Exchange rates for multi-currency support."""
    __tablename__ = "re_fx_rates"

    id              = Column(Integer, primary_key=True, index=True)
    org_id = Column(Integer, ForeignKey("organizations.id"), nullable=True, index=True)
    from_currency   = Column(String(10), nullable=False)
    to_currency     = Column(String(10), nullable=False)
    rate            = Column(Float, nullable=False)
    valid_date      = Column(Date, nullable=False)
    created_at      = Column(DateTime(timezone=True), server_default=func.now())


class IpcHistory(Base):
    """
    Tracks IPC revisions applied to conditions.
    All linked conditions must be updated simultaneously.
    """
    __tablename__ = "re_ipc_history"

    id              = Column(Integer, primary_key=True, index=True)
    contract_id     = Column(Integer, ForeignKey("re_contracts.id"), nullable=False)
    applied_date    = Column(Date, nullable=False)
    old_index       = Column(Float, nullable=False)
    new_index       = Column(Float, nullable=False)
    revision_pct    = Column(Float, nullable=False)   # (new/old - 1) * 100
    conditions_updated = Column(JSON, default=list)   # List of condition IDs updated
    created_at      = Column(DateTime(timezone=True), server_default=func.now())


class Ifrs16Schedule(Base):
    """
    IFRS 16 amortization schedule for a contract.
    One row per period — tracks liability balance and RoU balance.
    """
    __tablename__ = "re_ifrs16_schedules"

    id                  = Column(Integer, primary_key=True, index=True)
    contract_id         = Column(Integer, ForeignKey("re_contracts.id"), nullable=False, unique=True)

    # Initial recognition
    discount_rate       = Column(Float, nullable=False)   # IBR — incremental borrowing rate
    initial_liability   = Column(Numeric(18, 4))          # PV of future lease payments
    initial_rou         = Column(Numeric(18, 4))          # = initial_liability + initial direct costs
    initial_direct_costs= Column(Numeric(18, 4), default=0)
    recognition_date    = Column(Date, nullable=False)
    currency            = Column(String(10), default="USD")

    # Current balances (updated each posting run)
    liability_balance   = Column(Numeric(18, 4))
    rou_balance         = Column(Numeric(18, 4))
    accumulated_amort   = Column(Numeric(18, 4), default=0)

    # Amortization method
    rou_useful_life_months = Column(Integer)              # For straight-line depreciation
    amort_method        = Column(String(20), default="straight_line")

    last_posted_date    = Column(Date, nullable=True)
    created_at          = Column(DateTime(timezone=True), server_default=func.now())
    updated_at          = Column(DateTime(timezone=True), onupdate=func.now())


class Ifrs16ScheduleLine(Base):
    """
    One period line of the IFRS 16 amortization table.
    Generated when the schedule is created or modified.
    """
    __tablename__ = "re_ifrs16_schedule_lines"

    id              = Column(Integer, primary_key=True, index=True)
    schedule_id     = Column(Integer, ForeignKey("re_ifrs16_schedules.id"), nullable=False)
    period_date     = Column(Date, nullable=False)         # First day of period

    lease_payment   = Column(Numeric(18, 4))               # Contractual payment
    interest_charge = Column(Numeric(18, 4))               # liability_balance × rate/12
    liability_repay = Column(Numeric(18, 4))               # payment - interest
    liability_close = Column(Numeric(18, 4))               # Closing balance
    rou_amort       = Column(Numeric(18, 4))               # Straight-line depreciation
    rou_close       = Column(Numeric(18, 4))               # RoU closing balance

    posted          = Column(Boolean, default=False)
