import React, { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    nav: {
      overview: 'Overview',
      commercial: 'Commercial',
      hospitality: 'Hospitality',
      admin: 'Admin',
      dashboard: 'Dashboard',
      revenueMap: 'Revenue Map',
      hotels: 'Hotels',
      rooms: 'Rooms',
      guests: 'Guests',
      bookings: 'Bookings',
      users: 'Users',
      auditLog: 'Audit Log',
      settings: 'My Settings',
      signOut: 'Sign Out',
    },
    dashboard: {
      title: 'Dashboard',
      updatedAt: 'Updated at',
      globalView: 'Global View',
      commercial: 'Commercial',
      hotels: 'Hotels',
      refresh: 'Refresh',
      loading: 'Loading…',
      error: 'Unable to load dashboard data.',
      retry: 'Retry',
      financeTitle: 'Finance & Revenue',
      financeSub: 'Collected revenue, invoices and trends',
      revenueThisMonth: 'Revenue this month',
      totalRevenue: 'Total revenue',
      sinceBeginning: 'Since the beginning',
      pendingInvoices: 'Pending invoices',
      overdueInvoices: 'Overdue invoices',
      monthlyRevenue: 'Monthly revenue — last 12 months',
      vsPrevMonth: 'vs prev. month',
      occupancyTitle: 'Occupancy & Vacancy',
      occupancySub: 'Real-time occupancy rates',
      commercialReal: 'Commercial Real Estate',
      hotelsLabel: 'Hotels',
      occupancyRate: 'Occupancy rate',
      excellent: 'Excellent',
      average: 'Average',
      low: 'Low',
      occupiedTonight: 'e(s) tonight',
      available: 'Available',
      total: 'Total',
      occupancyTrend: 'Occupancy trend — last 6 months (commercial)',
      unitsOccupied: 'units occupied',
      cashflowTitle: 'Cash Flow',
      cashflowSub: 'Inflows, outflows and monthly net balance',
      inflowThisMonth: 'Inflows this month',
      outflowThisMonth: 'Outflows this month',
      netCashflow: 'Net balance',
      surplus: 'Surplus',
      deficit: 'Deficit',
      cashflowChart: 'Cash flow — last 12 months',
      inflows: 'Inflows',
      outflows: 'Outflows',
      assetsTitle: 'Assets',
      assetsSub: 'Complete portfolio inventory',
      commercialProperties: 'Commercial properties',
      activeProperties: 'Active properties',
      totalUnits: 'Total units',
      rentalUnits: 'Rental units',
      hotelsCount: 'Hotels',
      establishments: 'Establishments',
      totalRooms: 'Total rooms',
      managedRooms: 'Managed rooms',
      city: 'City',
      country: 'Country',
      propertiesCol: 'Properties',
      hotelsCol: 'Hotels',
    },
    common: {
      add: 'Add',
      edit: 'Edit',
      delete: 'Delete',
      save: 'Save',
      cancel: 'Cancel',
      create: 'Create',
      search: 'Search…',
      noResults: 'No results found.',
      confirm: 'Confirm',
      actions: 'Actions',
      loading: 'Loading…',
      error: 'An error occurred.',
      deleteConfirm: 'This cannot be undone.',
      deleteFailed: 'Delete failed — this item may have dependencies.',
    },
    commercial: {
      // Patrimoine
      patrimoineTitle: 'Patrimoine',
      patrimoineSub: 'Architectural view — Business Entity → Building → Floor → Space',
      businessEntities: 'Business Entities',
      buildings: 'Buildings',
      floors: 'Floors',
      spaces: 'Spaces',
      newBusinessEntity: 'New Business Entity',
      newBuilding: 'New Building',
      newFloor: 'New Floor',
      newSpace: 'New Space',
      noEntities: 'No business entities yet.',
      noBuildings: 'No buildings.',
      noFloors: 'No floors.',
      noSpaces: 'No spaces on this floor.',
      name: 'Name',
      legalName: 'Legal Name',
      taxId: 'Tax ID',
      currency: 'Currency',
      country: 'Country',
      city: 'City',
      continent: 'Continent',
      address: 'Address',
      totalArea: 'Total Area (m²)',
      constructionYear: 'Construction Year',
      floorNumber: 'Floor Number',
      floorName: 'Name (e.g. Ground Floor)',
      areaSqm: 'Area (m²)',
      spaceCode: 'Space Code',
      description: 'Description',
      status: 'Status',
      initialMeasurement: 'Initial Measurement (time-dependent)',
      validFrom: 'Valid From',
      allEntities: 'All Entities',
      // Business Partners
      partnersTitle: 'Business Partners',
      partnersSub: 'Tenants, landlords, guarantors and vendors',
      newPartner: 'New Partner',
      companyName: 'Company Name',
      tradeName: 'Trade Name',
      contactName: 'Contact Name',
      phone: 'Phone',
      email: 'Email',
      roles: 'Roles',
      addRole: '+ Role',
      customerAccount: 'Customer Account (AR)',
      noPartners: 'No partners found',
      noPartnersDesc: 'Create your first business partner to get started.',
      arWarning: 'No Customer Account set — AR postings will be blocked for this tenant.',
      savePartner: 'Save Partner',
      // Contracts
      contractsTitle: 'Contracts',
      contractsSub: 'Commercial lease contracts — LO/LI',
      newContract: 'New Contract',
      contractNumber: 'Contract Number',
      contractType: 'Type',
      leaseOut: 'Lease Out (LO) — Landlord → Tenant',
      leaseIn: 'Lease In (LI) — Tenant from Landlord',
      businessEntity: 'Business Entity',
      businessPartner: 'Business Partner (Tenant)',
      keyDates: 'Key Dates (time-dependent)',
      datesInfo: 'Any modification to these dates creates a new time slot. The contract cannot be posted until status is Released.',
      startDate: 'Start Date',
      firstEndDate: 'First End Date',
      probableEndDate: 'Probable End Date',
      absoluteEndDate: 'Absolute End Date',
      noticeDate: 'Notice Date',
      signingDate: 'Signing Date',
      postingParams: 'Posting Parameters',
      paymentTiming: 'Payment Timing',
      inAdvance: 'In Advance (start of month)',
      inArrears: 'In Arrears (end of month)',
      dayCountMethod: 'Day Count Method',
      proRata: 'Enable pro-rata (partial month)',
      salesRelevant: 'Relevant to Sales (sales-based rent)',
      multiObject: 'Multi-object contract',
      rentalObjects: 'Rental Objects',
      notes: 'Notes',
      draftWarning: 'Contract will be created in Draft status. No FI postings will be generated until status is changed to Released.',
      createContract: 'Create Contract',
      releaseContract: 'Release Contract',
      releaseInfo: 'Ready to release? Once Released, FI postings will begin generating.',
      noContracts: 'No contracts found.',
      // Conditions
      conditionsTitle: 'Conditions',
      conditionsSub: 'Time-dependent rent & charge conditions',
      newCondition: 'New Condition',
      conditionType: 'Condition Type',
      conditionCode: 'Condition Code',
      amount: 'Amount',
      frequency: 'Frequency',
      monthly: 'Monthly',
      quarterly: 'Quarterly',
      semiAnnual: 'Semi-Annual',
      annual: 'Annual',
      ipcIndexation: 'IPC Indexation',
      enableIpc: 'Enable IPC indexation',
      ipcWarning: 'IPC revision must be applied simultaneously on all linked conditions (*40 and *50 before ACE, only *40 after ACE).',
      flatRate: 'Flat Rate — not reconciled (tenant pays fixed amount regardless of actual costs)',
      flatRateNote: 'Flat rates (e.g. Unibail A500) are never reconciled at SCS settlement.',
      markupFeeNote: 'Markup fees are statistical — they apply on the charged amount, not on rent. Common rates: 0%, 5%, 13%, 15%.',
      saveCondition: 'Save Condition',
      noConditions: 'No conditions found.',
      // Rental Objects
      rentalObjectsTitle: 'Rental Objects',
      rentalObjectsSub: 'Usage view — one or more physical spaces grouped into a leasable unit',
      newRentalObject: 'New Rental Object',
      usageType: 'Usage Type',
      costCenter: 'Cost Center (for vacancy postings)',
      imKey: 'IM Key (fixed asset link)',
      assignSpaces: 'Assign Physical Spaces',
      noRentalObjects: 'No rental objects',
      noRentalObjectsDesc: 'Create spaces first, then group them into rental objects.',
      // Service Charges
      serviceChargesTitle: 'Service Charges',
      serviceChargesSub: 'Participation Groups, Settlement Units and Cost Collectors',
      newGroup: '+ New Group',
      chargeCategory: 'Charge Category',
      members: 'Members',
      addMember: 'Add member to group',
      maxCost: 'Max Cost (cap)',
      markupRate: 'Markup Rate',
      excludeFromScs: 'Exclude from SCS',
      costCollectors: 'Cost Collectors',
      addCostCollector: '+ Add Cost Collector',
      totalCosts: 'Total Costs',
      ancillaryRevenues: 'Ancillary Revenues (reduces pool)',
      netPool: 'Net Pool to distribute',
      fiscalYear: 'Fiscal Year',
      noGroups: 'No participation groups',
      noGroupsDesc: 'Create a group to start distributing service charges.',
      scsInfo: 'Vacant units are always excluded from SCS. Ancillary revenues (parking, waste) reduce the pool before distribution — they do not add to landlord revenue.',
      capNote: 'Cap: excess distributed to uncapped tenants (MaxCostsSU).',
      ccWarning: 'Cost Collector must be in Released status before any charge postings. Once Settled, it rejects new postings.',
    },
    hotel: {
      hotelsTitle: 'Hotels',
      hotelsSub: 'Hotel property portfolio',
      hotelName: 'Hotel Name',
      stars: 'Stars',
      selectStars: '— Select Stars —',
      roomsTitle: 'Rooms',
      roomsSub: 'Room inventory and availability',
      selectHotel: '— Select Hotel —',
      roomNumber: 'Room Number',
      roomType: 'Room Type',
      pricePerNight: 'Price per Night ($)',
      guestsTitle: 'Guests',
      guestsSub: 'Guest profiles and history',
      firstName: 'First Name',
      lastName: 'Last Name',
      nationality: 'Nationality',
      idNumber: 'ID / Passport Number',
      bookingsTitle: 'Bookings',
      bookingsSub: 'Reservations and check-ins',
      selectGuest: '— Select Guest —',
      selectRoom: '— Select Room —',
      checkIn: 'Check-in',
      checkOut: 'Check-out',
      totalPrice: 'Total Price ($)',
      confirmed: 'Confirmed',
      checkedIn: 'Checked In',
      checkedOut: 'Checked Out',
      cancelled: 'Cancelled',
    },
    users: {
      title: 'Users',
      sub: 'Manage user accounts and roles',
      fullName: 'Full Name',
      email: 'Email',
      role: 'Role',
      password: 'Password',
      active: 'Active',
    },
    audit: {
      title: 'Audit Log',
      sub: 'Track all system activity',
    },
    settings: {
      title: 'My Settings',
      sub: 'Update your profile and preferences',
      language: 'Language',
    },
  },

  fr: {
    nav: {
      overview: 'Vue d\'ensemble',
      commercial: 'Commercial',
      hospitality: 'Hôtellerie',
      admin: 'Administration',
      dashboard: 'Tableau de bord',
      revenueMap: 'Carte des revenus',
      hotels: 'Hôtels',
      rooms: 'Chambres',
      guests: 'Clients',
      bookings: 'Réservations',
      users: 'Utilisateurs',
      auditLog: 'Journal d\'audit',
      settings: 'Mes paramètres',
      signOut: 'Se déconnecter',
    },
    dashboard: {
      title: 'Tableau de bord',
      updatedAt: 'Mis à jour à',
      globalView: 'Vue globale',
      commercial: 'Commercial',
      hotels: 'Hôtels',
      refresh: 'Actualiser',
      loading: 'Chargement…',
      error: 'Impossible de charger les données du tableau de bord.',
      retry: 'Réessayer',
      financeTitle: 'Finance & Revenus',
      financeSub: 'Revenus encaissés, factures et tendances',
      revenueThisMonth: 'Revenus ce mois',
      totalRevenue: 'Revenus totaux',
      sinceBeginning: 'Depuis le début',
      pendingInvoices: 'Factures en attente',
      overdueInvoices: 'Factures en retard',
      monthlyRevenue: 'Revenus mensuels — 12 derniers mois',
      vsPrevMonth: 'vs mois préc.',
      occupancyTitle: 'Occupation & Vacance',
      occupancySub: 'Taux d\'occupation en temps réel',
      commercialReal: 'Immobilier commercial',
      hotelsLabel: 'Hôtels',
      occupancyRate: 'Taux d\'occupation',
      excellent: 'Excellent',
      average: 'Moyen',
      low: 'Faible',
      occupiedTonight: 'e(s) ce soir',
      available: 'Disponible(s)',
      total: 'Total',
      occupancyTrend: 'Tendance d\'occupation — 6 derniers mois (commercial)',
      unitsOccupied: 'unités occupées',
      cashflowTitle: 'Flux de Trésorerie',
      cashflowSub: 'Entrées, sorties et solde net mensuel',
      inflowThisMonth: 'Entrées ce mois',
      outflowThisMonth: 'Sorties ce mois',
      netCashflow: 'Solde net',
      surplus: 'Excédent',
      deficit: 'Déficit',
      cashflowChart: 'Flux de trésorerie — 12 derniers mois',
      inflows: 'Entrées',
      outflows: 'Sorties',
      assetsTitle: 'Actifs',
      assetsSub: 'Inventaire complet du portefeuille',
      commercialProperties: 'Propriétés commerciales',
      activeProperties: 'Propriétés actives',
      totalUnits: 'Unités totales',
      rentalUnits: 'Unités locatives',
      hotelsCount: 'Hôtels',
      establishments: 'Établissements',
      totalRooms: 'Chambres totales',
      managedRooms: 'Chambres gérées',
      city: 'Ville',
      country: 'Pays',
      propertiesCol: 'Propriétés',
      hotelsCol: 'Hôtels',
    },
    common: {
      add: 'Ajouter',
      edit: 'Modifier',
      delete: 'Supprimer',
      save: 'Enregistrer',
      cancel: 'Annuler',
      create: 'Créer',
      search: 'Rechercher…',
      noResults: 'Aucun résultat trouvé.',
      confirm: 'Confirmer',
      actions: 'Actions',
      loading: 'Chargement…',
      error: 'Une erreur est survenue.',
      deleteConfirm: 'Cette action est irréversible.',
      deleteFailed: 'Suppression échouée — cet élément a peut-être des dépendances.',
    },
    commercial: {
      patrimoineTitle: 'Patrimoine',
      patrimoineSub: 'Vue architecturale — Entité juridique → Bâtiment → Étage → Espace',
      businessEntities: 'Entités juridiques',
      buildings: 'Bâtiments',
      floors: 'Étages',
      spaces: 'Espaces',
      newBusinessEntity: 'Nouvelle entité juridique',
      newBuilding: 'Nouveau bâtiment',
      newFloor: 'Nouvel étage',
      newSpace: 'Nouvel espace',
      noEntities: 'Aucune entité juridique.',
      noBuildings: 'Aucun bâtiment.',
      noFloors: 'Aucun étage.',
      noSpaces: 'Aucun espace sur cet étage.',
      name: 'Nom',
      legalName: 'Raison sociale',
      taxId: 'N° fiscal',
      currency: 'Devise',
      country: 'Pays',
      city: 'Ville',
      continent: 'Continent',
      address: 'Adresse',
      totalArea: 'Superficie totale (m²)',
      constructionYear: 'Année de construction',
      floorNumber: 'Numéro d\'étage',
      floorName: 'Nom (ex. Rez-de-chaussée)',
      areaSqm: 'Superficie (m²)',
      spaceCode: 'Code espace',
      description: 'Description',
      status: 'Statut',
      initialMeasurement: 'Mesure initiale (time-dependent)',
      validFrom: 'Valide dès',
      allEntities: 'Toutes les entités',
      partnersTitle: 'Partenaires d\'affaires',
      partnersSub: 'Locataires, bailleurs, garants et fournisseurs',
      newPartner: 'Nouveau partenaire',
      companyName: 'Nom de la société',
      tradeName: 'Nom commercial',
      contactName: 'Nom du contact',
      phone: 'Téléphone',
      email: 'Courriel',
      roles: 'Rôles',
      addRole: '+ Rôle',
      customerAccount: 'Compte client (AR)',
      noPartners: 'Aucun partenaire trouvé',
      noPartnersDesc: 'Créez votre premier partenaire pour commencer.',
      arWarning: 'Aucun compte client défini — les écritures AR seront bloquées pour ce locataire.',
      savePartner: 'Enregistrer le partenaire',
      contractsTitle: 'Contrats',
      contractsSub: 'Contrats de bail commercial — LO/LI',
      newContract: 'Nouveau contrat',
      contractNumber: 'Numéro de contrat',
      contractType: 'Type',
      leaseOut: 'Bail propriétaire (LO) — Bailleur → Locataire',
      leaseIn: 'Bail locataire (LI) — Locataire de bailleur',
      businessEntity: 'Entité juridique',
      businessPartner: 'Partenaire d\'affaires (Locataire)',
      keyDates: 'Dates clés (time-dependent)',
      datesInfo: 'Toute modification de ces dates crée un nouveau time slot. Le contrat ne peut pas être posté tant qu\'il est en statut Brouillon.',
      startDate: 'Date de début',
      firstEndDate: 'Première date de fin',
      probableEndDate: 'Date de fin probable',
      absoluteEndDate: 'Date de fin absolue',
      noticeDate: 'Date de préavis',
      signingDate: 'Date de signature',
      postingParams: 'Paramètres de comptabilisation',
      paymentTiming: 'Timing de paiement',
      inAdvance: 'En avance (début de mois)',
      inArrears: 'À terme échu (fin de mois)',
      dayCountMethod: 'Méthode de calcul des jours',
      proRata: 'Activer le pro-rata (mois partiel)',
      salesRelevant: 'Lié au CA (loyer basé sur le chiffre d\'affaires)',
      multiObject: 'Contrat multi-objets',
      rentalObjects: 'Objets locatifs',
      notes: 'Notes',
      draftWarning: 'Le contrat sera créé en statut Brouillon. Aucune écriture ne sera générée tant que le statut n\'est pas Validé.',
      createContract: 'Créer le contrat',
      releaseContract: 'Valider le contrat',
      releaseInfo: 'Prêt à valider ? Une fois validé, les écritures commenceront à être générées.',
      noContracts: 'Aucun contrat trouvé.',
      conditionsTitle: 'Conditions',
      conditionsSub: 'Conditions de loyer et de charges (time-dependent)',
      newCondition: 'Nouvelle condition',
      conditionType: 'Type de condition',
      conditionCode: 'Code condition',
      amount: 'Montant',
      frequency: 'Fréquence',
      monthly: 'Mensuel',
      quarterly: 'Trimestriel',
      semiAnnual: 'Semestriel',
      annual: 'Annuel',
      ipcIndexation: 'Indexation IPC',
      enableIpc: 'Activer l\'indexation IPC',
      ipcWarning: 'La révision IPC doit être appliquée simultanément sur toutes les conditions liées (*40 et *50 avant ACE, uniquement *40 après ACE).',
      flatRate: 'Forfait — non réconcilié (le locataire paie un montant fixe quel que soit le coût réel)',
      flatRateNote: 'Les forfaits (ex. Unibail A500) ne sont jamais réconciliés au settlement SCS.',
      markupFeeNote: 'Les frais de gestion sont statistiques — ils s\'appliquent sur le montant des charges, pas sur le loyer. Taux courants : 0%, 5%, 13%, 15%.',
      saveCondition: 'Enregistrer la condition',
      noConditions: 'Aucune condition trouvée.',
      rentalObjectsTitle: 'Objets locatifs',
      rentalObjectsSub: 'Vue d\'utilisation — un ou plusieurs espaces physiques groupés en unité locative',
      newRentalObject: 'Nouvel objet locatif',
      usageType: 'Type d\'utilisation',
      costCenter: 'Centre de coût (pour les vacances)',
      imKey: 'Clé IM (lien actif immobilisé)',
      assignSpaces: 'Assigner des espaces physiques',
      noRentalObjects: 'Aucun objet locatif',
      noRentalObjectsDesc: 'Créez d\'abord des espaces, puis regroupez-les en objets locatifs.',
      serviceChargesTitle: 'Charges locatives',
      serviceChargesSub: 'Groupes de participation, unités de settlement et collecteurs de coûts',
      newGroup: '+ Nouveau groupe',
      chargeCategory: 'Catégorie de charge',
      members: 'Membres',
      addMember: 'Ajouter un locataire au groupe',
      maxCost: 'Coût max (plafond)',
      markupRate: 'Taux de gestion',
      excludeFromScs: 'Exclure du SCS',
      costCollectors: 'Collecteurs de coûts',
      addCostCollector: '+ Ajouter un collecteur',
      totalCosts: 'Coûts totaux',
      ancillaryRevenues: 'Revenus annexes (réduit le pool)',
      netPool: 'Pool net à distribuer',
      fiscalYear: 'Exercice fiscal',
      noGroups: 'Aucun groupe de participation',
      noGroupsDesc: 'Créez un groupe pour commencer à répartir les charges.',
      scsInfo: 'Les unités vacantes sont toujours exclues du SCS. Les revenus annexes (parking, déchets) réduisent le pool avant répartition — ils ne s\'ajoutent pas aux revenus du bailleur.',
      capNote: 'Plafond : l\'excédent est réparti sur les locataires sans plafond (MaxCostsSU).',
      ccWarning: 'Le collecteur de coûts doit être en statut Validé avant tout posting de charges. Une fois Soldé, il rejette tout nouveau posting.',
    },
    hotel: {
      hotelsTitle: 'Hôtels',
      hotelsSub: 'Portefeuille d\'établissements hôteliers',
      hotelName: 'Nom de l\'hôtel',
      stars: 'Étoiles',
      selectStars: '— Sélectionner les étoiles —',
      roomsTitle: 'Chambres',
      roomsSub: 'Inventaire et disponibilité des chambres',
      selectHotel: '— Sélectionner un hôtel —',
      roomNumber: 'Numéro de chambre',
      roomType: 'Type de chambre',
      pricePerNight: 'Prix par nuit ($)',
      guestsTitle: 'Clients',
      guestsSub: 'Profils et historique des clients',
      firstName: 'Prénom',
      lastName: 'Nom de famille',
      nationality: 'Nationalité',
      idNumber: 'N° pièce d\'identité / passeport',
      bookingsTitle: 'Réservations',
      bookingsSub: 'Réservations et enregistrements',
      selectGuest: '— Sélectionner un client —',
      selectRoom: '— Sélectionner une chambre —',
      checkIn: 'Arrivée',
      checkOut: 'Départ',
      totalPrice: 'Prix total ($)',
      confirmed: 'Confirmé',
      checkedIn: 'Enregistré',
      checkedOut: 'Parti',
      cancelled: 'Annulé',
    },
    users: {
      title: 'Utilisateurs',
      sub: 'Gérer les comptes et les rôles',
      fullName: 'Nom complet',
      email: 'Courriel',
      role: 'Rôle',
      password: 'Mot de passe',
      active: 'Actif',
    },
    audit: {
      title: 'Journal d\'audit',
      sub: 'Suivre toute l\'activité du système',
    },
    settings: {
      title: 'Mes paramètres',
      sub: 'Mettre à jour votre profil et vos préférences',
      language: 'Langue',
    },
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('lang') || 'en');

  const toggleLanguage = () => {
    const next = language === 'en' ? 'fr' : 'en';
    setLanguage(next);
    localStorage.setItem('lang', next);
  };

  const t = translations[language];

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
