import React, { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    // Sidebar sections
    nav: {
      overview: 'Overview',
      commercial: 'Commercial',
      hospitality: 'Hospitality',
      admin: 'Admin',
      dashboard: 'Dashboard',
      revenueMap: 'Revenue Map',
      properties: 'Properties',
      units: 'Units',
      tenants: 'Tenants',
      invoices: 'Invoices',
      maintenance: 'Maintenance',
      hotels: 'Hotels',
      rooms: 'Rooms',
      guests: 'Guests',
      bookings: 'Bookings',
      users: 'Users',
      auditLog: 'Audit Log',
      settings: 'My Settings',
      signOut: 'Sign Out',
    },
    // Dashboard
    dashboard: {
      title: 'Dashboard',
      updatedAt: 'Updated at',
      globalView: 'Global View',
      commercial: 'Commercial',
      hotels: 'Hotels',
      refresh: 'Refresh',
      loading: 'Loading…',
      error: 'Unable to load dashboard data.',
      retry: 'Retry',
      // Finance
      financeTitle: 'Finance & Revenue',
      financeSub: 'Collected revenue, invoices and trends',
      revenueThisMonth: 'Revenue this month',
      totalRevenue: 'Total revenue',
      sinceBeginning: 'Since the beginning',
      pendingInvoices: 'Pending invoices',
      overdueInvoices: 'Overdue invoices',
      monthlyRevenue: 'Monthly revenue — last 12 months',
      vsPrevMonth: 'vs prev. month',
      // Occupancy
      occupancyTitle: 'Occupancy & Vacancy',
      occupancySub: 'Real-time occupancy rates',
      commercialReal: 'Commercial Real Estate',
      hotelsLabel: 'Hotels',
      occupancyRate: 'Occupancy rate',
      excellent: 'Excellent',
      average: 'Average',
      low: 'Low',
      occupiedTonight: 'e(s) tonight',
      available: 'Available',
      total: 'Total',
      occupancyTrend: 'Occupancy trend — last 6 months (commercial)',
      unitsOccupied: 'units occupied',
      // Cashflow
      cashflowTitle: 'Cash Flow',
      cashflowSub: 'Inflows, outflows and monthly net balance',
      inflowThisMonth: 'Inflows this month',
      outflowThisMonth: 'Outflows this month',
      netCashflow: 'Net balance',
      surplus: 'Surplus',
      deficit: 'Deficit',
      cashflowChart: 'Cash flow — last 12 months',
      inflows: 'Inflows',
      outflows: 'Outflows',
      // Assets
      assetsTitle: 'Assets',
      assetsSub: 'Complete portfolio inventory',
      commercialProperties: 'Commercial properties',
      activeProperties: 'Active properties',
      totalUnits: 'Total units',
      rentalUnits: 'Rental units',
      hotelsCount: 'Hotels',
      establishments: 'Establishments',
      totalRooms: 'Total rooms',
      managedRooms: 'Managed rooms',
      city: 'City',
      country: 'Country',
      propertiesCol: 'Properties',
      hotelsCol: 'Hotels',
    },
    // CrudPage / common
    common: {
      add: 'Add',
      edit: 'Edit',
      delete: 'Delete',
      save: 'Save',
      cancel: 'Cancel',
      search: 'Search…',
      noResults: 'No results found.',
      confirm: 'Confirm',
      actions: 'Actions',
      loading: 'Loading…',
      error: 'An error occurred.',
    },
    // RetailPages
    retail: {
      propertiesTitle: 'Properties',
      propertiesSub: 'Commercial property portfolio',
      propertyName: 'Property Name',
      address: 'Address',
      city: 'City',
      country: 'Country',
      continent: 'Continent',
      selectCountry: '— Select Country —',
      selectContinent: '— Select Continent —',
      totalArea: 'Total Area (sqft)',
      annualRevenue: 'Annual Revenue ($)',
      area: 'Area',
      unitsTitle: 'Units',
      unitsSub: 'Rentable spaces and status',
      property: 'Property',
      selectProperty: '— Select Property —',
      unitNumber: 'Unit Number',
      floor: 'Floor',
      areaSqft: 'Area (sqft)',
      unitType: 'Unit Type',
      monthlyRent: 'Monthly Rent ($)',
      status: 'Status',
      available: 'Available',
      occupied: 'Occupied',
      maintenanceStatus: 'Maintenance',
      tenantsTitle: 'Tenants',
      tenantsSub: 'Tenant leases and contacts',
      selectUnit: '— Select Unit —',
      businessName: 'Business Name',
      contactName: 'Contact Name',
      phone: 'Phone',
      email: 'Email',
      leaseStart: 'Lease Start',
      leaseEnd: 'Lease End',
      securityDeposit: 'Security Deposit ($)',
      leaseStatus: 'Lease Status',
      active: 'Active',
      pending: 'Pending',
      expired: 'Expired',
      terminated: 'Terminated',
      invoicesTitle: 'Invoices',
      invoicesSub: 'Rent payments and balances',
      selectTenant: '— Select Tenant —',
      amount: 'Amount ($)',
      dueDate: 'Due Date',
      paidDate: 'Paid Date',
      paid: 'Paid',
      overdue: 'Overdue',
      description: 'Description',
      maintenanceTitle: 'Maintenance',
      maintenanceSub: 'Track and resolve requests',
      title: 'Title',
      priority: 'Priority',
      priorityLow: 'Low',
      priorityMedium: 'Medium',
      priorityHigh: 'High',
      priorityUrgent: 'Urgent',
      open: 'Open',
      inProgress: 'In Progress',
      closed: 'Closed',
      reportedBy: 'Reported By',
      date: 'Date',
      noContact: 'No contact',
      rent: 'Rent/mo',
    },
    // HotelPages
    hotel: {
      hotelsTitle: 'Hotels',
      hotelsSub: 'Hotel property portfolio',
      hotelName: 'Hotel Name',
      stars: 'Stars',
      selectStars: '— Select Stars —',
      roomsTitle: 'Rooms',
      roomsSub: 'Room inventory and availability',
      selectHotel: '— Select Hotel —',
      roomNumber: 'Room Number',
      roomType: 'Room Type',
      pricePerNight: 'Price per Night ($)',
      guestsTitle: 'Guests',
      guestsSub: 'Guest profiles and history',
      firstName: 'First Name',
      lastName: 'Last Name',
      nationality: 'Nationality',
      idNumber: 'ID / Passport Number',
      bookingsTitle: 'Bookings',
      bookingsSub: 'Reservations and check-ins',
      selectGuest: '— Select Guest —',
      selectRoom: '— Select Room —',
      checkIn: 'Check-in',
      checkOut: 'Check-out',
      totalPrice: 'Total Price ($)',
      confirmed: 'Confirmed',
      checkedIn: 'Checked In',
      checkedOut: 'Checked Out',
      cancelled: 'Cancelled',
    },
    // Users / Auth
    users: {
      title: 'Users',
      sub: 'Manage user accounts and roles',
      fullName: 'Full Name',
      email: 'Email',
      role: 'Role',
      password: 'Password',
      active: 'Active',
    },
    // Audit
    audit: {
      title: 'Audit Log',
      sub: 'Track all system activity',
    },
    // Settings
    settings: {
      title: 'My Settings',
      sub: 'Update your profile and preferences',
      language: 'Language',
    },
  },

  fr: {
    nav: {
      overview: 'Vue d\'ensemble',
      commercial: 'Commercial',
      hospitality: 'Hôtellerie',
      admin: 'Administration',
      dashboard: 'Tableau de bord',
      revenueMap: 'Carte des revenus',
      properties: 'Propriétés',
      units: 'Unités',
      tenants: 'Locataires',
      invoices: 'Factures',
      maintenance: 'Maintenance',
      hotels: 'Hôtels',
      rooms: 'Chambres',
      guests: 'Clients',
      bookings: 'Réservations',
      users: 'Utilisateurs',
      auditLog: 'Journal d\'audit',
      settings: 'Mes paramètres',
      signOut: 'Se déconnecter',
    },
    dashboard: {
      title: 'Tableau de bord',
      updatedAt: 'Mis à jour à',
      globalView: 'Vue globale',
      commercial: 'Commercial',
      hotels: 'Hôtels',
      refresh: 'Actualiser',
      loading: 'Chargement…',
      error: 'Impossible de charger les données du tableau de bord.',
      retry: 'Réessayer',
      financeTitle: 'Finance & Revenus',
      financeSub: 'Revenus encaissés, factures et tendances',
      revenueThisMonth: 'Revenus ce mois',
      totalRevenue: 'Revenus totaux',
      sinceBeginning: 'Depuis le début',
      pendingInvoices: 'Factures en attente',
      overdueInvoices: 'Factures en retard',
      monthlyRevenue: 'Revenus mensuels — 12 derniers mois',
      vsPrevMonth: 'vs mois préc.',
      occupancyTitle: 'Occupation & Vacance',
      occupancySub: 'Taux d\'occupation en temps réel',
      commercialReal: 'Immobilier commercial',
      hotelsLabel: 'Hôtels',
      occupancyRate: 'Taux d\'occupation',
      excellent: 'Excellent',
      average: 'Moyen',
      low: 'Faible',
      occupiedTonight: 'e(s) ce soir',
      available: 'Disponible(s)',
      total: 'Total',
      occupancyTrend: 'Tendance d\'occupation — 6 derniers mois (commercial)',
      unitsOccupied: 'unités occupées',
      cashflowTitle: 'Flux de Trésorerie',
      cashflowSub: 'Entrées, sorties et solde net mensuel',
      inflowThisMonth: 'Entrées ce mois',
      outflowThisMonth: 'Sorties ce mois',
      netCashflow: 'Solde net',
      surplus: 'Excédent',
      deficit: 'Déficit',
      cashflowChart: 'Flux de trésorerie — 12 derniers mois',
      inflows: 'Entrées',
      outflows: 'Sorties',
      assetsTitle: 'Actifs',
      assetsSub: 'Inventaire complet du portefeuille',
      commercialProperties: 'Propriétés commerciales',
      activeProperties: 'Propriétés actives',
      totalUnits: 'Unités totales',
      rentalUnits: 'Unités locatives',
      hotelsCount: 'Hôtels',
      establishments: 'Établissements',
      totalRooms: 'Chambres totales',
      managedRooms: 'Chambres gérées',
      city: 'Ville',
      country: 'Pays',
      propertiesCol: 'Propriétés',
      hotelsCol: 'Hôtels',
    },
    common: {
      add: 'Ajouter',
      edit: 'Modifier',
      delete: 'Supprimer',
      save: 'Enregistrer',
      cancel: 'Annuler',
      search: 'Rechercher…',
      noResults: 'Aucun résultat trouvé.',
      confirm: 'Confirmer',
      actions: 'Actions',
      loading: 'Chargement…',
      error: 'Une erreur est survenue.',
    },
    retail: {
      propertiesTitle: 'Propriétés',
      propertiesSub: 'Portefeuille de propriétés commerciales',
      propertyName: 'Nom de la propriété',
      address: 'Adresse',
      city: 'Ville',
      country: 'Pays',
      continent: 'Continent',
      selectCountry: '— Sélectionner un pays —',
      selectContinent: '— Sélectionner un continent —',
      totalArea: 'Superficie totale (pi²)',
      annualRevenue: 'Revenu annuel ($)',
      area: 'Superficie',
      unitsTitle: 'Unités',
      unitsSub: 'Espaces locatifs et statut',
      property: 'Propriété',
      selectProperty: '— Sélectionner une propriété —',
      unitNumber: 'Numéro d\'unité',
      floor: 'Étage',
      areaSqft: 'Superficie (pi²)',
      unitType: 'Type d\'unité',
      monthlyRent: 'Loyer mensuel ($)',
      status: 'Statut',
      available: 'Disponible',
      occupied: 'Occupé',
      maintenanceStatus: 'Maintenance',
      tenantsTitle: 'Locataires',
      tenantsSub: 'Baux et contacts des locataires',
      selectUnit: '— Sélectionner une unité —',
      businessName: 'Nom de l\'entreprise',
      contactName: 'Nom du contact',
      phone: 'Téléphone',
      email: 'Courriel',
      leaseStart: 'Début du bail',
      leaseEnd: 'Fin du bail',
      securityDeposit: 'Dépôt de garantie ($)',
      leaseStatus: 'Statut du bail',
      active: 'Actif',
      pending: 'En attente',
      expired: 'Expiré',
      terminated: 'Résilié',
      invoicesTitle: 'Factures',
      invoicesSub: 'Paiements de loyer et soldes',
      selectTenant: '— Sélectionner un locataire —',
      amount: 'Montant ($)',
      dueDate: 'Date d\'échéance',
      paidDate: 'Date de paiement',
      paid: 'Payé',
      overdue: 'En retard',
      description: 'Description',
      maintenanceTitle: 'Maintenance',
      maintenanceSub: 'Suivre et résoudre les demandes',
      title: 'Titre',
      priority: 'Priorité',
      priorityLow: 'Faible',
      priorityMedium: 'Moyenne',
      priorityHigh: 'Haute',
      priorityUrgent: 'Urgente',
      open: 'Ouvert',
      inProgress: 'En cours',
      closed: 'Fermé',
      reportedBy: 'Signalé par',
      date: 'Date',
      noContact: 'Sans contact',
      rent: 'Loyer/mois',
    },
    hotel: {
      hotelsTitle: 'Hôtels',
      hotelsSub: 'Portefeuille d\'établissements hôteliers',
      hotelName: 'Nom de l\'hôtel',
      stars: 'Étoiles',
      selectStars: '— Sélectionner les étoiles —',
      roomsTitle: 'Chambres',
      roomsSub: 'Inventaire et disponibilité des chambres',
      selectHotel: '— Sélectionner un hôtel —',
      roomNumber: 'Numéro de chambre',
      roomType: 'Type de chambre',
      pricePerNight: 'Prix par nuit ($)',
      guestsTitle: 'Clients',
      guestsSub: 'Profils et historique des clients',
      firstName: 'Prénom',
      lastName: 'Nom de famille',
      nationality: 'Nationalité',
      idNumber: 'N° pièce d\'identité / passeport',
      bookingsTitle: 'Réservations',
      bookingsSub: 'Réservations et enregistrements',
      selectGuest: '— Sélectionner un client —',
      selectRoom: '— Sélectionner une chambre —',
      checkIn: 'Arrivée',
      checkOut: 'Départ',
      totalPrice: 'Prix total ($)',
      confirmed: 'Confirmé',
      checkedIn: 'Enregistré',
      checkedOut: 'Parti',
      cancelled: 'Annulé',
    },
    users: {
      title: 'Utilisateurs',
      sub: 'Gérer les comptes et les rôles',
      fullName: 'Nom complet',
      email: 'Courriel',
      role: 'Rôle',
      password: 'Mot de passe',
      active: 'Actif',
    },
    audit: {
      title: 'Journal d\'audit',
      sub: 'Suivre toute l\'activité du système',
    },
    settings: {
      title: 'Mes paramètres',
      sub: 'Mettre à jour votre profil et vos préférences',
      language: 'Langue',
    },
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('lang') || 'en');

  const toggleLanguage = () => {
    const next = language === 'en' ? 'fr' : 'en';
    setLanguage(next);
    localStorage.setItem('lang', next);
  };

  const t = translations[language];

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
