import React, { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    nav: {
      overview: 'Overview', commercial: 'Commercial', hospitality: 'Hospitality',
      admin: 'Admin', dashboard: 'Dashboard', revenueMap: 'Revenue Map',
      hotels: 'Hotels', rooms: 'Rooms', guests: 'Guests', bookings: 'Bookings',
      users: 'Users', auditLog: 'Audit Log', settings: 'My Settings', signOut: 'Sign Out',
    },
    common: {
      add: 'Add', edit: 'Edit', delete: 'Delete', save: 'Save', cancel: 'Cancel',
      create: 'Create', search: 'Search…', noResults: 'No results found.',
      confirm: 'Confirm', actions: 'Actions', loading: 'Loading…', error: 'An error occurred.',
      deleteConfirm: 'This cannot be undone.', deleteFailed: 'Delete failed — this item may have dependencies.',
      saveChanges: 'Save Changes', viewDetails: 'View', allRoles: 'All Roles',
      noData: 'No data yet.', active: 'Active', expired: 'Expired',
    },
    dashboard: {
      title: 'Dashboard', updatedAt: 'Updated at', globalView: 'Global View',
      commercial: 'Commercial', hotels: 'Hotels', refresh: 'Refresh',
      loading: 'Loading…', error: 'Unable to load dashboard data.', retry: 'Retry',
      financeTitle: 'Finance & Revenue', financeSub: 'Collected revenue, invoices and trends',
      revenueThisMonth: 'Revenue this month', totalRevenue: 'Total revenue',
      sinceBeginning: 'Since the beginning', pendingInvoices: 'Pending invoices',
      overdueInvoices: 'Overdue invoices', monthlyRevenue: 'Monthly revenue — last 12 months',
      vsPrevMonth: 'vs prev. month', occupancyTitle: 'Occupancy & Vacancy',
      occupancySub: 'Real-time occupancy rates', commercialReal: 'Commercial Real Estate',
      hotelsLabel: 'Hotels', occupancyRate: 'Occupancy rate',
      excellent: 'Excellent', average: 'Average', low: 'Low',
      occupiedTonight: 'e(s) tonight', available: 'Available', total: 'Total',
      occupancyTrend: 'Occupancy trend — last 6 months (commercial)', unitsOccupied: 'units occupied',
      cashflowTitle: 'Cash Flow', cashflowSub: 'Inflows, outflows and monthly net balance',
      inflowThisMonth: 'Inflows this month', outflowThisMonth: 'Outflows this month',
      netCashflow: 'Net balance', surplus: 'Surplus', deficit: 'Deficit',
      cashflowChart: 'Cash flow — last 12 months', inflows: 'Inflows', outflows: 'Outflows',
      assetsTitle: 'Assets', assetsSub: 'Complete portfolio inventory',
      commercialProperties: 'Commercial properties', activeProperties: 'Active properties',
      totalUnits: 'Total units', rentalUnits: 'Rental units', hotelsCount: 'Hotels',
      establishments: 'Establishments', totalRooms: 'Total rooms', managedRooms: 'Managed rooms',
      city: 'City', country: 'Country', propertiesCol: 'Properties', hotelsCol: 'Hotels',
    },
    commercial: {
      // Patrimoine
      patrimoineTitle: 'Patrimoine', patrimoineSub: 'Architectural view — Business Entity → Building → Floor → Space',
      businessEntities: 'Business Entities', buildings: 'Buildings', floors: 'Floors', spaces: 'Spaces',
      newBusinessEntity: 'New Business Entity', newBuilding: 'New Building', newFloor: 'New Floor', newSpace: 'New Space',
      noEntities: 'No business entities yet.', noBuildings: 'No buildings.', noFloors: 'No floors.', noSpaces: 'No spaces on this floor.',
      name: 'Name', legalName: 'Legal Name', taxId: 'Tax ID', currency: 'Currency',
      country: 'Country', city: 'City', continent: 'Continent', address: 'Address',
      totalArea: 'Total Area (m²)', constructionYear: 'Construction Year',
      floorNumber: 'Floor Number', floorName: 'Name (e.g. Ground Floor)',
      areaSqm: 'Area (m²)', spaceCode: 'Space Code', description: 'Description',
      status: 'Status', initialMeasurement: 'Initial Measurement (time-dependent)',
      validFrom: 'Valid From', allEntities: 'All Entities',
      // Business Partners
      partnersTitle: 'Business Partners', partnersSub: 'Tenants, landlords, guarantors and vendors',
      newPartner: 'New Partner', companyName: 'Company Name', tradeName: 'Trade Name',
      contactName: 'Contact Name', phone: 'Phone', email: 'Email',
      roles: 'Roles', addRole: '+ Role', customerAccount: 'Customer Account (AR)',
      noPartners: 'No partners found', noPartnersDesc: 'Create your first business partner to get started.',
      arWarning: 'No Customer Account set — AR postings will be blocked for this tenant.',
      savePartner: 'Save Partner', editPartner: 'Edit Partner',
      filterAllRoles: 'All Roles', bpNumber: 'BP Number',
      masterTenant: 'Master Tenant', guarantor: 'Guarantor', landlord: 'Landlord',
      vendor: 'Vendor', contactPerson: 'Contact',
      // Contracts
      contractsTitle: 'Contracts', contractsSub: 'Commercial lease contracts — LO/LI',
      newContract: 'New Contract', contractNumber: 'Contract Number',
      contractType: 'Type', leaseOut: 'Lease Out (LO) — Landlord → Tenant',
      leaseIn: 'Lease In (LI) — Tenant from Landlord',
      businessEntity: 'Business Entity', businessPartner: 'Business Partner (Tenant)',
      keyDates: 'Key Dates (time-dependent)',
      datesInfo: 'Any modification to these dates creates a new time slot. The contract cannot be posted until status is Released.',
      startDate: 'Start Date', firstEndDate: 'First End Date', probableEndDate: 'Probable End Date',
      absoluteEndDate: 'Absolute End Date', noticeDate: 'Notice Date', signingDate: 'Signing Date',
      postingParams: 'Posting Parameters', paymentTiming: 'Payment Timing',
      inAdvance: 'In Advance (start of month)', inArrears: 'In Arrears (end of month)',
      dayCountMethod: 'Day Count Method', proRata: 'Enable pro-rata (partial month)',
      salesRelevant: 'Relevant to Sales (sales-based rent)', multiObject: 'Multi-object contract',
      rentalObjectsLabel: 'Rental Objects', notes: 'Notes',
      draftWarning: 'Contract will be created in Draft status. No FI postings until Released.',
      createContract: 'Create Contract', releaseContract: 'Release Contract',
      releaseInfo: 'Ready to release? Once Released, FI postings will begin generating.',
      noContracts: 'No contracts found.', expiringWarning: 'contract(s) expiring within 90 days',
      expiresIn: 'Expires in', daysAgo: 'days ago',
      conditions: 'Conditions', info: 'Info',
      deleteOnlyDraft: 'Only Draft contracts can be deleted.',
      // Conditions
      conditionsTitle: 'Conditions', conditionsSub: 'Time-dependent rent & charge conditions',
      newCondition: 'New Condition', conditionType: 'Condition Type', conditionCode: 'Condition Code',
      amount: 'Amount', frequency: 'Frequency', monthly: 'Monthly', quarterly: 'Quarterly',
      semiAnnual: 'Semi-Annual', annual: 'Annual', validTo: 'Valid To (empty = active)',
      ipcIndexation: 'IPC Indexation', enableIpc: 'Enable IPC indexation',
      ipcWarning: 'IPC revision must be applied simultaneously on all linked conditions (*40 and *50 before ACE, only *40 after ACE).',
      baseIndex: 'Base Index', referenceDate: 'Reference Date',
      flatRate: 'Flat Rate — not reconciled (tenant pays fixed amount regardless of actual costs)',
      flatRateNote: 'Flat rates (e.g. Unibail A500) are never reconciled at SCS settlement.',
      markupFeeNote: 'Markup fees are statistical — they apply on the charged amount, not on rent. Common rates: 0%, 5%, 13%, 15%.',
      markupRate: 'Markup Rate', saveCondition: 'Save Condition',
      noConditions: 'No conditions found.', allContracts: 'All Contracts', allTypes: 'All Types',
      paymentTimingLabel: 'Payment Timing', inAdvanceShort: 'In Advance', inArrearsShort: 'In Arrears',
      condTypeBaseRent: 'Base Rent', condTypeServiceCharge: 'Service Charge',
      condTypeAdvancePayment: 'Advance Payment', condTypeFlatRate: 'Flat Rate',
      condTypeSalesBased: 'Sales-Based Rent', condTypeMarkupFee: 'Markup Fee',
      condTypeRentFree: 'Rent-Free', condTypeAbatement: 'Abatement',
      // Rental Objects
      rentalObjectsTitle: 'Rental Objects', rentalObjectsSub: 'Usage view — one or more physical spaces grouped into a leasable unit',
      newRentalObject: 'New Rental Object', usageType: 'Usage Type',
      costCenter: 'Cost Center (for vacancy postings)', imKey: 'IM Key (fixed asset link)',
      assignSpaces: 'Assign Physical Spaces', selectBuilding: 'Select a building first.',
      noSpacesAvail: 'No available spaces in this building.',
      noRentalObjects: 'No rental objects', noRentalObjectsDesc: 'Create spaces first, then group them into rental objects.',
      physicalSpaces: 'Physical Spaces', activeContract: 'Active Contract',
      // Service Charges
      serviceChargesTitle: 'Service Charges', serviceChargesSub: 'Participation Groups, Settlement Units and Cost Collectors',
      newGroup: '+ New Group', chargeCategory: 'Charge Category',
      members: 'Members', addMemberHint: 'Click to add tenant:',
      maxCost: 'Max Cost (cap)', excludeFromScs: 'Exclude',
      costCollectors: 'Cost Collectors', addCostCollector: '+ Add Cost Collector',
      totalCosts: 'Total Costs', ancillaryRevenues: 'Ancillary Revenues (reduces pool)',
      netPool: 'Net Pool to distribute', fiscalYear: 'Fiscal Year',
      noGroups: 'No participation groups', noGroupsDesc: 'Create a group to start distributing service charges.',
      scsInfo: 'Vacant units are always excluded from SCS. Ancillary revenues (parking, waste) reduce the pool before distribution — they do not add to landlord revenue.',
      capNote: 'Cap: excess distributed to uncapped tenants (MaxCostsSU).',
      ccWarning: 'Cost Collector must be in Released status before any charge postings. Once Settled, it rejects new postings.',
      settle: 'Settle', settled: 'Settled', released: 'Released',
      activeMembers: 'active member', capped: 'capped', excluded: 'excluded',
      settlementUnits: 'settlement unit',
      // Posting Engine
      postingTitle: 'Posting Engine', postingSub: 'SAP RE-FX RERAPP-inspired — run period postings, IPC, IFRS 16',
      totalRuns: 'Total Runs', lastRunPeriod: 'Last Run Period', totalPosted: 'Total Posted',
      pendingIfrs16: 'Pending IFRS16 Lines', runPeriodPosting: 'Run Period Posting',
      periodFrom: 'Period From', periodTo: 'Period To', module: 'Module',
      dryRunLabel: 'Dry Run (Simulation)', liveRunLabel: 'Live Run (Will Post)',
      dryRunDesc: 'Calculates amounts without creating entries',
      liveRunDesc: 'Will generate real accounting entries',
      runSimulation: 'Run Simulation', runPosting: 'Run Posting', running: '⏳ Running…',
      otherActions: 'Other Actions', applyIpc: 'Apply IPC Revision',
      setupIfrs16: 'Setup IFRS 16 Schedule', runHistory: 'Run History',
      noRuns: 'No runs yet', noRunsDesc: 'Run a simulation to see results here.',
      totalEntries: 'Total Entries', totalAmount: 'Total Amount', errors: 'Errors',
      breakdownByType: 'Breakdown by Type', noEntries: 'No entries (dry run or no data).',
      type: 'Type', contract: 'Contract', period: 'Period', amount: 'Amount',
      // IPC Modal
      ipcModalTitle: 'Apply IPC Revision',
      ipcWarningModal: 'IPC revision will simultaneously update ALL linked conditions on this contract. Before ACE: *40 and *50. After ACE: *40 only.',
      newIndex: 'New IPC Index', appliedDate: 'Applied Date', applyIpcBtn: 'Apply IPC',
      ipcApplied: '✓ IPC Applied', oldIndex: 'Old Index', revisionPct: 'Revision',
      conditionsUpdated: 'Conditions Updated',
      // IFRS16 Modal
      ifrs16ModalTitle: 'Setup IFRS 16 Schedule',
      ifrs16Info: 'IFRS 16 initial recognition calculates the present value of all future lease payments using the Incremental Borrowing Rate (IBR). This builds the full amortization schedule.',
      discountRate: 'Discount Rate (IBR) — e.g. 0.045 for 4.5%',
      initialDirectCosts: 'Initial Direct Costs', buildSchedule: 'Build Schedule',
      ifrs16Created: '✓ IFRS 16 Schedule Created',
      initialLiability: 'Initial Liability (PV)', rouAsset: 'Right-of-Use Asset',
      usefulLife: 'Useful Life', recognitionDate: 'Recognition Date',
      // Module labels
      modAll: 'All Modules', modRent: 'Rent Only', modScs: 'Service Charges',
      modSales: 'Sales-Based Rent', modVacancy: 'Vacancy Postings',
      modDeposit: 'Security Deposits', modIfrs16: 'IFRS 16',
    },
    hotel: {
      hotelsTitle: 'Hotels', hotelsSub: 'Hotel property portfolio', hotelName: 'Hotel Name',
      stars: 'Stars', selectStars: '— Select Stars —', roomsTitle: 'Rooms',
      roomsSub: 'Room inventory and availability', selectHotel: '— Select Hotel —',
      roomNumber: 'Room Number', roomType: 'Room Type', pricePerNight: 'Price per Night ($)',
      guestsTitle: 'Guests', guestsSub: 'Guest profiles and history',
      firstName: 'First Name', lastName: 'Last Name', nationality: 'Nationality',
      idNumber: 'ID / Passport Number', bookingsTitle: 'Bookings',
      bookingsSub: 'Reservations and check-ins', selectGuest: '— Select Guest —',
      selectRoom: '— Select Room —', checkIn: 'Check-in', checkOut: 'Check-out',
      totalPrice: 'Total Price ($)', confirmed: 'Confirmed', checkedIn: 'Checked In',
      checkedOut: 'Checked Out', cancelled: 'Cancelled',
    },
    users: {
      title: 'Users', sub: 'Manage user accounts and roles',
      fullName: 'Full Name', email: 'Email', role: 'Role', password: 'Password', active: 'Active',
    },
    audit: { title: 'Audit Log', sub: 'Track all system activity' },
    settings: { title: 'My Settings', sub: 'Update your profile and preferences', language: 'Language' },
  },

  fr: {
    nav: {
      overview: 'Vue d\'ensemble', commercial: 'Commercial', hospitality: 'Hôtellerie',
      admin: 'Administration', dashboard: 'Tableau de bord', revenueMap: 'Carte des revenus',
      hotels: 'Hôtels', rooms: 'Chambres', guests: 'Clients', bookings: 'Réservations',
      users: 'Utilisateurs', auditLog: 'Journal d\'audit', settings: 'Mes paramètres', signOut: 'Se déconnecter',
    },
    common: {
      add: 'Ajouter', edit: 'Modifier', delete: 'Supprimer', save: 'Enregistrer',
      cancel: 'Annuler', create: 'Créer', search: 'Rechercher…', noResults: 'Aucun résultat trouvé.',
      confirm: 'Confirmer', actions: 'Actions', loading: 'Chargement…', error: 'Une erreur est survenue.',
      deleteConfirm: 'Cette action est irréversible.',
      deleteFailed: 'Suppression échouée — cet élément a peut-être des dépendances.',
      saveChanges: 'Enregistrer les modifications', viewDetails: 'Voir', allRoles: 'Tous les rôles',
      noData: 'Aucune donnée.', active: 'Actif', expired: 'Expiré',
    },
    dashboard: {
      title: 'Tableau de bord', updatedAt: 'Mis à jour à', globalView: 'Vue globale',
      commercial: 'Commercial', hotels: 'Hôtels', refresh: 'Actualiser',
      loading: 'Chargement…', error: 'Impossible de charger les données.', retry: 'Réessayer',
      financeTitle: 'Finance & Revenus', financeSub: 'Revenus encaissés, factures et tendances',
      revenueThisMonth: 'Revenus ce mois', totalRevenue: 'Revenus totaux',
      sinceBeginning: 'Depuis le début', pendingInvoices: 'Factures en attente',
      overdueInvoices: 'Factures en retard', monthlyRevenue: 'Revenus mensuels — 12 derniers mois',
      vsPrevMonth: 'vs mois préc.', occupancyTitle: 'Occupation & Vacance',
      occupancySub: 'Taux d\'occupation en temps réel', commercialReal: 'Immobilier commercial',
      hotelsLabel: 'Hôtels', occupancyRate: 'Taux d\'occupation',
      excellent: 'Excellent', average: 'Moyen', low: 'Faible',
      occupiedTonight: 'e(s) ce soir', available: 'Disponible(s)', total: 'Total',
      occupancyTrend: 'Tendance d\'occupation — 6 derniers mois (commercial)', unitsOccupied: 'unités occupées',
      cashflowTitle: 'Flux de Trésorerie', cashflowSub: 'Entrées, sorties et solde net mensuel',
      inflowThisMonth: 'Entrées ce mois', outflowThisMonth: 'Sorties ce mois',
      netCashflow: 'Solde net', surplus: 'Excédent', deficit: 'Déficit',
      cashflowChart: 'Flux de trésorerie — 12 derniers mois', inflows: 'Entrées', outflows: 'Sorties',
      assetsTitle: 'Actifs', assetsSub: 'Inventaire complet du portefeuille',
      commercialProperties: 'Propriétés commerciales', activeProperties: 'Propriétés actives',
      totalUnits: 'Unités totales', rentalUnits: 'Unités locatives', hotelsCount: 'Hôtels',
      establishments: 'Établissements', totalRooms: 'Chambres totales', managedRooms: 'Chambres gérées',
      city: 'Ville', country: 'Pays', propertiesCol: 'Propriétés', hotelsCol: 'Hôtels',
    },
    commercial: {
      // Patrimoine
      patrimoineTitle: 'Patrimoine', patrimoineSub: 'Vue architecturale — Entité juridique → Bâtiment → Étage → Espace',
      businessEntities: 'Entités juridiques', buildings: 'Bâtiments', floors: 'Étages', spaces: 'Espaces',
      newBusinessEntity: 'Nouvelle entité juridique', newBuilding: 'Nouveau bâtiment',
      newFloor: 'Nouvel étage', newSpace: 'Nouvel espace',
      noEntities: 'Aucune entité juridique.', noBuildings: 'Aucun bâtiment.',
      noFloors: 'Aucun étage.', noSpaces: 'Aucun espace sur cet étage.',
      name: 'Nom', legalName: 'Raison sociale', taxId: 'N° fiscal', currency: 'Devise',
      country: 'Pays', city: 'Ville', continent: 'Continent', address: 'Adresse',
      totalArea: 'Superficie totale (m²)', constructionYear: 'Année de construction',
      floorNumber: 'Numéro d\'étage', floorName: 'Nom (ex. Rez-de-chaussée)',
      areaSqm: 'Superficie (m²)', spaceCode: 'Code espace', description: 'Description',
      status: 'Statut', initialMeasurement: 'Mesure initiale (time-dependent)',
      validFrom: 'Valide dès', allEntities: 'Toutes les entités',
      // Business Partners
      partnersTitle: 'Partenaires d\'affaires', partnersSub: 'Locataires, bailleurs, garants et fournisseurs',
      newPartner: 'Nouveau partenaire', companyName: 'Nom de la société', tradeName: 'Nom commercial',
      contactName: 'Nom du contact', phone: 'Téléphone', email: 'Courriel',
      roles: 'Rôles', addRole: '+ Rôle', customerAccount: 'Compte client (AR)',
      noPartners: 'Aucun partenaire trouvé', noPartnersDesc: 'Créez votre premier partenaire pour commencer.',
      arWarning: 'Aucun compte client défini — les écritures AR seront bloquées pour ce locataire.',
      savePartner: 'Enregistrer le partenaire', editPartner: 'Modifier le partenaire',
      filterAllRoles: 'Tous les rôles', bpNumber: 'Numéro BP',
      masterTenant: 'Locataire principal', guarantor: 'Garant', landlord: 'Bailleur',
      vendor: 'Fournisseur', contactPerson: 'Contact',
      // Contracts
      contractsTitle: 'Contrats', contractsSub: 'Contrats de bail commercial — LO/LI',
      newContract: 'Nouveau contrat', contractNumber: 'Numéro de contrat',
      contractType: 'Type', leaseOut: 'Bail propriétaire (LO) — Bailleur → Locataire',
      leaseIn: 'Bail locataire (LI) — Locataire de bailleur',
      businessEntity: 'Entité juridique', businessPartner: 'Partenaire d\'affaires (Locataire)',
      keyDates: 'Dates clés (time-dependent)',
      datesInfo: 'Toute modification de ces dates crée un nouveau time slot. Le contrat ne peut pas être posté en statut Brouillon.',
      startDate: 'Date de début', firstEndDate: 'Première date de fin',
      probableEndDate: 'Date de fin probable', absoluteEndDate: 'Date de fin absolue',
      noticeDate: 'Date de préavis', signingDate: 'Date de signature',
      postingParams: 'Paramètres de comptabilisation', paymentTiming: 'Timing de paiement',
      inAdvance: 'En avance (début de mois)', inArrears: 'À terme échu (fin de mois)',
      dayCountMethod: 'Méthode de calcul des jours', proRata: 'Activer le pro-rata (mois partiel)',
      salesRelevant: 'Lié au CA (loyer basé sur le chiffre d\'affaires)', multiObject: 'Contrat multi-objets',
      rentalObjectsLabel: 'Objets locatifs', notes: 'Notes',
      draftWarning: 'Le contrat sera créé en statut Brouillon. Aucune écriture tant que le statut n\'est pas Validé.',
      createContract: 'Créer le contrat', releaseContract: 'Valider le contrat',
      releaseInfo: 'Prêt à valider ? Une fois validé, les écritures commenceront à être générées.',
      noContracts: 'Aucun contrat trouvé.', expiringWarning: 'contrat(s) expirant dans 90 jours',
      expiresIn: 'Expire dans', daysAgo: 'jours écoulés',
      conditions: 'Conditions', info: 'Infos',
      deleteOnlyDraft: 'Seuls les contrats en Brouillon peuvent être supprimés.',
      // Conditions
      conditionsTitle: 'Conditions', conditionsSub: 'Conditions de loyer et de charges (time-dependent)',
      newCondition: 'Nouvelle condition', conditionType: 'Type de condition', conditionCode: 'Code condition',
      amount: 'Montant', frequency: 'Fréquence', monthly: 'Mensuel', quarterly: 'Trimestriel',
      semiAnnual: 'Semestriel', annual: 'Annuel', validTo: 'Valide jusqu\'au (vide = actif)',
      ipcIndexation: 'Indexation IPC', enableIpc: 'Activer l\'indexation IPC',
      ipcWarning: 'La révision IPC doit être appliquée simultanément sur toutes les conditions liées (*40 et *50 avant ACE, uniquement *40 après ACE).',
      baseIndex: 'Indice de base', referenceDate: 'Date de référence',
      flatRate: 'Forfait — non réconcilié (le locataire paie un montant fixe quel que soit le coût réel)',
      flatRateNote: 'Les forfaits (ex. Unibail A500) ne sont jamais réconciliés au settlement SCS.',
      markupFeeNote: 'Les frais de gestion sont statistiques — ils s\'appliquent sur le montant des charges, pas sur le loyer. Taux courants : 0%, 5%, 13%, 15%.',
      markupRate: 'Taux de gestion', saveCondition: 'Enregistrer la condition',
      noConditions: 'Aucune condition trouvée.', allContracts: 'Tous les contrats', allTypes: 'Tous les types',
      paymentTimingLabel: 'Timing de paiement', inAdvanceShort: 'En avance', inArrearsShort: 'À terme échu',
      condTypeBaseRent: 'Loyer de base', condTypeServiceCharge: 'Charges locatives',
      condTypeAdvancePayment: 'Avance sur charges', condTypeFlatRate: 'Forfait',
      condTypeSalesBased: 'Loyer basé sur CA', condTypeMarkupFee: 'Frais de gestion',
      condTypeRentFree: 'Franchise de loyer', condTypeAbatement: 'Abattement',
      // Rental Objects
      rentalObjectsTitle: 'Objets locatifs', rentalObjectsSub: 'Vue d\'utilisation — un ou plusieurs espaces physiques groupés en unité locative',
      newRentalObject: 'Nouvel objet locatif', usageType: 'Type d\'utilisation',
      costCenter: 'Centre de coût (pour les vacances)', imKey: 'Clé IM (lien actif immobilisé)',
      assignSpaces: 'Assigner des espaces physiques', selectBuilding: 'Sélectionnez d\'abord un bâtiment.',
      noSpacesAvail: 'Aucun espace disponible dans ce bâtiment.',
      noRentalObjects: 'Aucun objet locatif', noRentalObjectsDesc: 'Créez d\'abord des espaces, puis regroupez-les en objets locatifs.',
      physicalSpaces: 'Espaces physiques', activeContract: 'Contrat actif',
      // Service Charges
      serviceChargesTitle: 'Charges locatives', serviceChargesSub: 'Groupes de participation, unités de settlement et collecteurs de coûts',
      newGroup: '+ Nouveau groupe', chargeCategory: 'Catégorie de charge',
      members: 'Membres', addMemberHint: 'Cliquer pour ajouter un locataire :',
      maxCost: 'Coût max (plafond)', excludeFromScs: 'Exclure',
      costCollectors: 'Collecteurs de coûts', addCostCollector: '+ Ajouter un collecteur',
      totalCosts: 'Coûts totaux', ancillaryRevenues: 'Revenus annexes (réduit le pool)',
      netPool: 'Pool net à distribuer', fiscalYear: 'Exercice fiscal',
      noGroups: 'Aucun groupe de participation', noGroupsDesc: 'Créez un groupe pour commencer à répartir les charges.',
      scsInfo: 'Les unités vacantes sont toujours exclues du SCS. Les revenus annexes (parking, déchets) réduisent le pool avant répartition.',
      capNote: 'Plafond : l\'excédent est réparti sur les locataires sans plafond (MaxCostsSU).',
      ccWarning: 'Le collecteur de coûts doit être en statut Validé avant tout posting. Une fois Soldé, il rejette tout nouveau posting.',
      settle: 'Solder', settled: 'Soldé', released: 'Validé',
      activeMembers: 'membre actif', capped: 'plafonné', excluded: 'exclu',
      settlementUnits: 'unité de settlement',
      // Posting Engine
      postingTitle: 'Moteur de posting', postingSub: 'SAP RE-FX RERAPP — lancer les postings périodiques, IPC, IFRS 16',
      totalRuns: 'Runs totaux', lastRunPeriod: 'Dernière période', totalPosted: 'Total posté',
      pendingIfrs16: 'Lignes IFRS16 en attente', runPeriodPosting: 'Lancer un posting périodique',
      periodFrom: 'Période du', periodTo: 'Période au', module: 'Module',
      dryRunLabel: 'Simulation (Dry Run)', liveRunLabel: 'Run réel (sera posté)',
      dryRunDesc: 'Calcule les montants sans créer d\'écritures',
      liveRunDesc: 'Génère de vraies écritures comptables',
      runSimulation: 'Lancer la simulation', runPosting: 'Lancer le posting', running: '⏳ En cours…',
      otherActions: 'Autres actions', applyIpc: 'Appliquer une révision IPC',
      setupIfrs16: 'Configurer le planning IFRS 16', runHistory: 'Historique des runs',
      noRuns: 'Aucun run', noRunsDesc: 'Lancez une simulation pour voir les résultats.',
      totalEntries: 'Écritures totales', totalAmount: 'Montant total', errors: 'Erreurs',
      breakdownByType: 'Répartition par type', noEntries: 'Aucune écriture (dry run ou pas de données).',
      type: 'Type', contract: 'Contrat', period: 'Période', amount: 'Montant',
      // IPC Modal
      ipcModalTitle: 'Appliquer une révision IPC',
      ipcWarningModal: 'La révision IPC mettra à jour simultanément TOUTES les conditions liées. Avant ACE : *40 et *50. Après ACE : *40 uniquement.',
      newIndex: 'Nouvel indice IPC', appliedDate: 'Date d\'application', applyIpcBtn: 'Appliquer l\'IPC',
      ipcApplied: '✓ IPC appliqué', oldIndex: 'Ancien indice', revisionPct: 'Révision',
      conditionsUpdated: 'Conditions mises à jour',
      // IFRS16 Modal
      ifrs16ModalTitle: 'Configurer le planning IFRS 16',
      ifrs16Info: 'La reconnaissance initiale IFRS 16 calcule la valeur actuelle de tous les paiements futurs de loyer en utilisant le taux d\'emprunt marginal (IBR). Cela construit le tableau d\'amortissement complet.',
      discountRate: 'Taux d\'actualisation (IBR) — ex. 0.045 pour 4,5%',
      initialDirectCosts: 'Coûts directs initiaux', buildSchedule: 'Construire le planning',
      ifrs16Created: '✓ Planning IFRS 16 créé',
      initialLiability: 'Passif initial (VA)', rouAsset: 'Actif de droit d\'utilisation (RoU)',
      usefulLife: 'Durée d\'utilité', recognitionDate: 'Date de reconnaissance',
      // Module labels
      modAll: 'Tous les modules', modRent: 'Loyer uniquement', modScs: 'Charges locatives',
      modSales: 'Loyer basé sur CA', modVacancy: 'Postings de vacance',
      modDeposit: 'Dépôts de garantie', modIfrs16: 'IFRS 16',
    },
    hotel: {
      hotelsTitle: 'Hôtels', hotelsSub: 'Portefeuille d\'établissements hôteliers', hotelName: 'Nom de l\'hôtel',
      stars: 'Étoiles', selectStars: '— Sélectionner les étoiles —', roomsTitle: 'Chambres',
      roomsSub: 'Inventaire et disponibilité des chambres', selectHotel: '— Sélectionner un hôtel —',
      roomNumber: 'Numéro de chambre', roomType: 'Type de chambre', pricePerNight: 'Prix par nuit ($)',
      guestsTitle: 'Clients', guestsSub: 'Profils et historique des clients',
      firstName: 'Prénom', lastName: 'Nom de famille', nationality: 'Nationalité',
      idNumber: 'N° pièce d\'identité / passeport', bookingsTitle: 'Réservations',
      bookingsSub: 'Réservations et enregistrements', selectGuest: '— Sélectionner un client —',
      selectRoom: '— Sélectionner une chambre —', checkIn: 'Arrivée', checkOut: 'Départ',
      totalPrice: 'Prix total ($)', confirmed: 'Confirmé', checkedIn: 'Enregistré',
      checkedOut: 'Parti', cancelled: 'Annulé',
    },
    users: {
      title: 'Utilisateurs', sub: 'Gérer les comptes et les rôles',
      fullName: 'Nom complet', email: 'Courriel', role: 'Rôle', password: 'Mot de passe', active: 'Actif',
    },
    audit: { title: 'Journal d\'audit', sub: 'Suivre toute l\'activité du système' },
    settings: { title: 'Mes paramètres', sub: 'Mettre à jour votre profil et vos préférences', language: 'Langue' },
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('lang') || 'en');
  const toggleLanguage = () => {
    const next = language === 'en' ? 'fr' : 'en';
    setLanguage(next); localStorage.setItem('lang', next);
  };
  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t: translations[language] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() { return useContext(LanguageContext); }
